# Generated by Django 6.1.1 on 2026-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('file', models.FileField(blank=True, upload_to='documents/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка (если файл не загружен)')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LocalContentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата')),
                ('body', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Материал: местное содержание',
                'verbose_name_plural': 'Местное содержание — материалы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('date', models.DateField(verbose_name='Дата')),
                ('excerpt', models.CharField(blank=True, max_length=400, verbose_name='Краткое описание')),
                ('body', models.TextField(blank=True, verbose_name='Текст новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название закупки')),
                ('status', models.CharField(choices=[('Открыт', 'Открыт'), ('Завершён', 'Завершён')], default='Открыт', max_length=20, verbose_name='Статус')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок подачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка (тендерная площадка/файл)')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
                'ordering': ['-deadline'],
            },
        ),
    ]
