# Generated by Django 6.1.1 on 2026-09-28 11:04

"""RichTextField → StreamField (блоки: текст, таблица, Markdown, HTML).

Прежний HTML каждой страницы — и в самой странице, и во всех её ревизиях
(черновики, история версий) — становится одним блоком «Текст», чтобы
ничего не потерялось и редактор открывал старые версии.
"""
import json
import uuid

import wagtail.fields
from django.db import migrations

FIELDS = [
    ("localcontentpage", "body"),
    ("newspage", "body"),
    ("procurementpage", "description"),
]


def html_to_stream(html):
    if not html:
        return "[]"
    return json.dumps([{"type": "text", "value": html, "id": str(uuid.uuid4())}])


def stream_to_html(raw):
    try:
        blocks = json.loads(raw or "[]")
    except (TypeError, ValueError):
        return raw or ""
    return "".join(b["value"] for b in blocks if b.get("type") == "text")


def convert(apps, convert_value):
    ContentType = apps.get_model("contenttypes.ContentType")
    Revision = apps.get_model("wagtailcore.Revision")
    for model_name, field in FIELDS:
        model = apps.get_model("content", model_name)
        for page in model.objects.all():
            setattr(page, field, convert_value(getattr(page, field)))
            page.save(update_fields=[field])

        content_type = ContentType.objects.filter(app_label="content", model=model_name).first()
        if content_type is None:
            continue
        for revision in Revision.objects.filter(content_type=content_type):
            if field in revision.content:
                revision.content[field] = convert_value(revision.content[field])
                revision.save(update_fields=["content"])


def forwards(apps, schema_editor):
    convert(apps, html_to_stream)


def backwards(apps, schema_editor):
    convert(apps, stream_to_html)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_create_site_tree'),
    ]

    operations = [
        # Сначала данные (пока колонка ещё текстовая), потом тип поля.
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='localcontentpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='procurementpage',
            name='description',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Описание'),
        ),
    ]
