# Generated by Django 6.1.1 on 2026-09-28 11:24

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_streamfield_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='category_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория (English)'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='category_kz',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория (қазақша)'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)'),
        ),
        migrations.AddField(
            model_name='localcontentpage',
            name='body_en',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст (English)'),
        ),
        migrations.AddField(
            model_name='localcontentpage',
            name='body_kz',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст (қазақша)'),
        ),
        migrations.AddField(
            model_name='localcontentpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)'),
        ),
        migrations.AddField(
            model_name='localcontentpage',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='body_en',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст новости (English)'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='body_kz',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст новости (қазақша)'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='excerpt_en',
            field=models.CharField(blank=True, max_length=400, verbose_name='Краткое описание (English)'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='excerpt_kz',
            field=models.CharField(blank=True, max_length=400, verbose_name='Краткое описание (қазақша)'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)'),
        ),
        migrations.AddField(
            model_name='procurementpage',
            name='description_en',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Описание (English)'),
        ),
        migrations.AddField(
            model_name='procurementpage',
            name='description_kz',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Описание (қазақша)'),
        ),
        migrations.AddField(
            model_name='procurementpage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)'),
        ),
        migrations.AddField(
            model_name='procurementpage',
            name='title_kz',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)'),
        ),
    ]
