# Generated by Django 6.1.1 on 2026-09-28 11:37

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_translations'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('teaser', models.CharField(blank=True, max_length=300, verbose_name='Кратко (для карточки)')),
                ('body', wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Описание проекта')),
                ('title_kz', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)')),
                ('region_kz', models.CharField(blank=True, max_length=100, verbose_name='Регион (қазақша)')),
                ('teaser_kz', models.CharField(blank=True, max_length=300, verbose_name='Кратко (қазақша)')),
                ('body_kz', wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Описание проекта (қазақша)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)')),
                ('region_en', models.CharField(blank=True, max_length=100, verbose_name='Регион (English)')),
                ('teaser_en', models.CharField(blank=True, max_length=300, verbose_name='Кратко (English)')),
                ('body_en', wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Описание проекта (English)')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProjectsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Раздел «Проекты»',
            },
            bases=('wagtailcore.page',),
        ),
    ]
