# Generated by Django 6.1.1 on 2026-09-28 12:11

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_create_projects'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('title_kz', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)')),
            ],
            options={
                'verbose_name': 'Закупки: подраздел',
                'verbose_name_plural': 'Закупки: подразделы',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='procurementpage',
            options={'verbose_name': 'Закупки: запись', 'verbose_name_plural': 'Закупки: записи'},
        ),
        migrations.AddField(
            model_name='procurementpage',
            name='attachments',
            field=wagtail.fields.StreamField([('file', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Файл'})}, help_text='Документы для скачивания (PDF, XLSX…) — из библиотеки «Документы» или загрузить новые.', verbose_name='Файлы'),
        ),
        migrations.AddField(
            model_name='procurementpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='procurementpage',
            name='description',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='procurementpage',
            name='description_en',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст (English)'),
        ),
        migrations.AlterField(
            model_name='procurementpage',
            name='description_kz',
            field=wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст (қазақша)'),
        ),
        migrations.AlterField(
            model_name='procurementpage',
            name='status',
            field=models.CharField(blank=True, choices=[('Открыт', 'Открыт'), ('Завершён', 'Завершён')], default='', help_text='Необязательно — для объявлений о закупках, у которых есть приём заявок.', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='procurementpage',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка (тендерная площадка и т.п.)'),
        ),
    ]
