# Generated by Django 6.1.1 on 2026-09-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_rename_url_external_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementpage',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='procurementpage',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='procurementpage',
            name='status',
        ),
    ]
