# Generated by Django 6.1.1 on 2026-09-28 13:11

import content.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_procurement_status_deadline_url'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='ТОО «PSA»', max_length=100, verbose_name='Название организации')),
                ('tagline', models.CharField(blank=True, max_length=255, verbose_name='Подпись под названием')),
                ('address', models.TextField(blank=True, help_text='Каждая строка — с новой строки.', verbose_name='Адрес')),
                ('phones', wagtail.fields.StreamField([('phone', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: +7 7172 79 89 20', 'label': 'Номер'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Например: Канцелярия', 'label': 'Пояснение', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Пояснение (қазақша)', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Пояснение (English)', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('number', 0), ('note', 1), ('note_kz', 2), ('note_en', 3)]], {})}, verbose_name='Телефоны')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('mail_url', models.URLField(blank=True, verbose_name='Ссылка «Почта» (корпоративная почта)')),
                ('org_name_kz', models.CharField(blank=True, max_length=100, verbose_name='Название организации (қазақша)')),
                ('tagline_kz', models.CharField(blank=True, max_length=255, verbose_name='Подпись под названием (қазақша)')),
                ('address_kz', models.TextField(blank=True, verbose_name='Адрес (қазақша)')),
                ('org_name_en', models.CharField(blank=True, max_length=100, verbose_name='Название организации (English)')),
                ('tagline_en', models.CharField(blank=True, max_length=255, verbose_name='Подпись под названием (English)')),
                ('address_en', models.TextField(blank=True, verbose_name='Адрес (English)')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Подвал сайта',
            },
            bases=(content.models.TranslatedFieldsMixin, models.Model),
        ),
    ]
