# Generated by Django 6.1.1 on 2026-09-28 15:48

import content.models
import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_fill_footer_settings'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Раздел «Маркетинг»',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MarketingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('description', wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст')),
                ('attachments', wagtail.fields.StreamField([('file', 0)], blank=True, block_lookup={0: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Файл'})}, help_text='Документы для скачивания (PDF, XLSX…) — из библиотеки «Документы» или загрузить новые.', verbose_name='Файлы')),
                ('title_kz', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)')),
                ('description_kz', wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст (қазақша)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)')),
                ('description_en', wagtail.fields.StreamField([('text', 0), ('table', 1), ('markdown', 2), ('html', 3)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': 'Текст'}), 1: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'label': 'Таблица', 'table_options': {'contextMenu': ['row_above', 'row_below', '---------', 'col_left', 'col_right', '---------', 'remove_row', 'remove_col', '---------', 'mergeCells', 'alignment', '---------', 'undo', 'redo'], 'height': 216, 'mergeCells': True, 'startCols': 3, 'startRows': 3}}), 2: ('content.blocks.MarkdownBlock', (), {}), 3: ('wagtail.blocks.RawHTMLBlock', (), {'help_text': 'Вставляется на страницу как есть, без проверки — только для доверенного кода.', 'label': 'HTML'})}, verbose_name='Текст (English)')),
            ],
            options={
                'verbose_name': 'Маркетинг: запись',
                'verbose_name_plural': 'Маркетинг: записи',
            },
            bases=(content.models.TranslatedFieldsMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='MarketingSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('title_kz', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (қазақша)')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Заголовок (English)')),
            ],
            options={
                'verbose_name': 'Маркетинг: подраздел',
                'verbose_name_plural': 'Маркетинг: подразделы',
            },
            bases=(content.models.TranslatedFieldsMixin, 'wagtailcore.page'),
        ),
    ]
