# Generated by Django 6.1.1 on 2026-09-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.TextField(blank=True, help_text='Адреса e-mail — каждый с новой строки или через запятую. Пусто — письма не отправляются, обращения только сохраняются в разделе «Обращения».', verbose_name='Кому отправлять обращения')),
                ('subject', models.CharField(default='Обращение с сайта PSA', max_length=200, verbose_name='Тема письма')),
            ],
            options={
                'verbose_name': 'Форма «Контакты»',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Получено')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('language', models.CharField(blank=True, choices=[('ru', 'Русский'), ('kz', 'Қазақша'), ('en', 'English')], max_length=2, verbose_name='Язык сайта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Письмо отправлено')),
                ('email_error', models.TextField(blank=True, verbose_name='Ошибка отправки письма')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='Например, smtp.mail.ru, smtp.gmail.com или сервер корпоративной почты. Пусто — письма не отправляются, а только пишутся в лог сервера.', max_length=255, verbose_name='SMTP-сервер')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='Порт')),
                ('security', models.CharField(choices=[('tls', 'STARTTLS — обычно порт 587'), ('ssl', 'SSL/TLS — обычно порт 465'), ('none', 'Без шифрования — обычно порт 25')], default='tls', max_length=10, verbose_name='Шифрование')),
                ('username', models.CharField(blank=True, help_text='Обычно — полный адрес почтового ящика.', max_length=255, verbose_name='Логин')),
                ('password', models.CharField(blank=True, help_text='Для Gmail, Mail.ru, Яндекса — «пароль приложения» из настроек безопасности ящика, а не обычный пароль.', max_length=255, verbose_name='Пароль')),
                ('from_email', models.EmailField(blank=True, help_text='От чьего имени приходят письма. Обычно совпадает с логином — многие серверы не разрешают другой.', max_length=254, verbose_name='Адрес отправителя')),
                ('from_name', models.CharField(blank=True, default='ТОО «PSA»', max_length=100, verbose_name='Имя отправителя')),
            ],
            options={
                'verbose_name': 'Почта (SMTP)',
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Посетители видят страницу «Сайт на техническом обслуживании» (503). Админка работает, вошедшие в неё сотрудники видят сайт как обычно — можно проверить изменения до открытия.', verbose_name='Режим обслуживания')),
            ],
            options={
                'verbose_name': 'Сайт',
            },
        ),
    ]
