# Generated by Django 6.1.1 on 2026-09-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_contact_form_and_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='verify_certificate',
            field=models.BooleanField(default=True, help_text='Снимите галочку, если у почтового сервера самоподписанный сертификат (обычно у Exchange внутри организации). Соединение останется зашифрованным, но подлинность сервера не проверяется — только для сервера во внутренней сети.', verbose_name='Проверять сертификат сервера'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='security',
            field=models.CharField(choices=[('tls', 'STARTTLS — обычно порт 587'), ('ssl', 'SSL/TLS — обычно порт 465'), ('none', 'Без шифрования — обычно порт 25')], default='tls', help_text='Exchange: порт 587 и STARTTLS — без шифрования Exchange не принимает логин и пароль.', max_length=10, verbose_name='Шифрование'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='username',
            field=models.CharField(blank=True, help_text='Обычно — полный адрес почтового ящика. Exchange: также ДОМЕН\\логин или логин@домен.local.', max_length=255, verbose_name='Логин'),
        ),
    ]
